#!/bin/bash
printer() {
  printf "%s" "$1"
}
export -f printer

message="Hello World!"

for (( i=0; i<${#message}; i++ )); do
  printf "%s\0" "${message:$i:1}"
done | xargs -0 -n 1 -P 4 bash -c 'printer "$@"' --

printf "\n"
