CC=gcc-4.7
FLAGS=-O2 -Wall -Wextra

BIN=parhello

all: test

test: $(BIN)
	./$(BIN)

$(BIN): parhello.c
	$(CC) $(FLAGS) -fopenmp -o $(BIN) parhello.c

splint:
	find . -type f -name '*.c' -exec splint {} \;
	find . -type f -name '*.h' -exec splint {} \;

vera++:
	find . -type f -name '*.cpp' -exec vera++ -s {} \;
	find . -type f -name '*.c' -exec vera++ -s {} \;
	find . -type f -name '*.h' -exec vera++ -s {} \;

lint: splint vera++

valgrind: $(BIN)
	valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --track-fds=yes --dsymutil=yes ./$(BIN)

clean:
	-rm *.exe
	-rm $(BIN)
